apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: db-interaction-service
    provider: fabric8
    group: com.redhat.fuse.boosters
  name: db-interaction-service
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: db-interaction-service
    provider: fabric8
    group: com.redhat.fuse.boosters
  strategy:
    rollingParams:
      timeoutSeconds: 3600
    type: Rolling
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: true
      labels:
        app: db-interaction-service
        provider: fabric8
        group: com.redhat.fuse.boosters
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: db-interaction-service
      containers:
      - name: db-interaction-service
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 100
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator
            port: 8080
          initialDelaySeconds: 200
          periodSeconds: 10
        volumeMounts:
          - name: config-volume
            mountPath: /deployments/application.properties
            subPath: application.properties
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - db-interaction-service
      from:
        kind: ImageStreamTag
        name: db-interaction-service:latest
    type: ImageChange